### ISSUE TITLE
Image in the center of the QR code

### ISSUE THREAD

**Issue by ingeJulianLasso** [Cordobo/angularx-qrcode#114]
Hello, thank you very much for such an excellent library. I would like to ask if it is possible to add a custom image in the center of the QR code that is generated with the library.

I have observed that this library depends on another one called "qrcode" and I consulted a little bit, I could see that it is possible to insert an image in the center of the QR code that is generated.

https://stackoverflow.com/questions/53898890/how-to-generate-qr-code-together-with-the-image-in-a-center#answers-header

Can you tell me how to do this? Thank you very much for the help you can give me

**Comment by Mondei1** [comment]
Hey! I figured it out myself. I put the QR-Code into a div and then I put a absolute image over it. I just struggled with centering it (typical CSS :roll_eyes:) but since my QR-Code and icon is always 256px and 32px in height/width respectively, I calculated 96px as distance from top and left for the icon.

### Code
CSS
```css
.qr {
    width: 256px;
    height: 256px;
    border-radius: 8px;
    overflow: hidden;
}

/* Only this is relevant for the icon */
.qr > img {
    position: absolute;
    height: 64px;
    width: 64px;
    top: 96px;
    left: 96px;
    z-index: 2;
}
```

HTML
```html
<div class="qr">
    <img src="assets/Bitcoin.svg">    <!-- Your icon -->
    <qrcode
        [qrdata]="'bitcoin:1QFrbboisCYgeBdowGAuCTK3r2YnZuApYd'"
        [width]="256"
        [errorCorrectionLevel]="'M'"
        [elementType]="'svg'"
        [margin]="1">
    </qrcode>
</div>
```

And this is how it looks *(still scanable)*:
![image](https://user-images.githubusercontent.com/22984849/103142769-b0b71b80-4709-11eb-888f-2bf78c023fba.png)

So no, there is not a "native" way with this library (yet) but it can be added very easily.

**Hope this helps you!**
